config/routes.rb
Rails.application.routes.draw do
  
  root 'application#signin'
  
  get 'app_pages/signin'

  get 'app_pages/filter'

  get 'app_pages/book'

  resources :appointments
  resources :doctors
  resources :organizations
  

end

app/controllers/app_pages_controller.rb
class AppPagesController < ApplicationController
  def signin
  end
  
  def filter
    @organizations = Organization.all
    @doctors = Doctor.all
    @doctor = Doctor.find(1)
    @appointments = Appointment.all
  end

  def book
    @organizations = Organization.all
    @doctors = Doctor.all
    @doctor = Doctor.find(1)
    @appointments = Appointment.all
  end
end

app/helpers/app_pages_helper.rb
module AppPagesHelper
end

app/views/app_pages/book.html.erb
<!--<nav class="navbar navbar-default">-->
<!--  <div class="container-fluid">-->
    <!-- Brand and toggle get grouped for better mobile display -->
<!--    <div class="navbar-header">-->
<!--      <a class="navbar-brand" href="#">Brand</a>-->
<!--    </div>-->
<!--    <div class="navbar-header navbar-right">-->
<!--      <p class="navbar-text">Signed in as <%= @doctor.name %></p>-->
<!--    </div>-->
<!--  </div><!-- /.container-fluid -->
<!--</nav>-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!--<a class="navbar-brand" href="#">Brand</a>-->
      <a class="navbar-left" href="#">
        <%=image_tag ("ConneXt.png"), :class => "logo" %>
        <!--<img src="assets/">-->
      </a>
    </div>
    <div class="navbar-header navbar-right">
      <p class="navbar-text">Signed in as <%= @doctor.name %></p>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div style="margin:20px" class="jumbotron">
    <div class="container">
  <h2>Select an Appointment</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Clinic</th>
        <th>Sliding Scale</th>
        <th>Doctor Name</th>
        <th>Doctor Gender</th>
        <th>Specialty</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
          <% if appointment.open? && (@doctors.find(appointment.doctor_id).specialty == "Pediatric" || @doctors.find(appointment.doctor_id).specialty == "Optometry") %>
            <td> <%= @organizations.find(@doctors.find(appointment.doctor_id).organization_id).name%></td>
            <td> <%= @organizations.find(@doctors.find(appointment.doctor_id).organization_id).sliding_scale%></td>
            <td> <%= @doctors.find(appointment.doctor_id).name %> </td>
            <td> <%= @doctors.find(appointment.doctor_id).gender %> </td>
            <td> <%= @doctors.find(appointment.doctor_id).specialty %></td>
            <td> <%= appointment.date %> </td>
            <td><%= link_to 'Book', edit_appointment_path(appointment), {:style =>'color:#FFFFFF;', :class=> "btn btn-lg btn-primary btn-block"} %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

<!--<div style="margin:none" class="navbar navbar-default navbar-fixed-bottom">-->
<!--  <div class="container">-->
<!--    <p class="navbar-text pull-left">© 2017 - D@M:AS.</p>-->
<!--  </div>-->
<!--</div>-->

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class = "container">
    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>
    <p class="navbar-text pull-left" display="inline-block">© 2017 - D@M:AS.</p>
  </div>
  <!--<div class="container">-->
  <!--  <a class="pull-right" href="#"> -->
  <!--    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>-->
  <!--</div> -->
</div>

app/views/app_pages/filter.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!--<a class="navbar-brand" href="#">Brand</a>-->
      <a class="navbar-left" href="#">
        <%=image_tag ("ConneXt.png"), :class => "logo" %>
        <!--<img src="assets/">-->
      </a>
    </div>
    <div class="navbar-header navbar-right">
      <p class="navbar-text">Signed in as <%= @doctor.name %></p>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div class="jumbotron col-sm-offset-1 col-sm-10">
  <form>
    <div class="form-group">
      <label for="exampleSelect2">Specialty</label>
      <select multiple class="form-control" id="exampleSelect2">
        <% @doctors.each do |doctor| %>
          <option> <%= doctor.specialty %></option>
        <% end %>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleSelect1">Doctor Gender</label>
      <select class="form-control" id="exampleSelect1">
        <option>--</option>
        <option>M</option>
        <option>F</option>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleSelect1">Medicare Covered</label>
      <select class="form-control" id="exampleSelect1">
        <option>--</option>
        <option>Y</option>
        <option>N</option>
      </select>
    </div>
    <%= link_to "Submit", app_pages_book_url, {:style =>'color:#FFFFFF;', :class=> "btn btn-lg btn-primary"} %>
  </form>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class = "container">
    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>
    <p class="navbar-text pull-left" display="inline-block">© 2017 - D@M:AS.</p>
  </div>
  <!--<div class="container">-->
  <!--  <a class="pull-right" href="#"> -->
  <!--    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>-->
  <!--</div> -->
</div>

app/views/app_pages/signin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!--<a class="navbar-brand" href="#">Brand</a>-->
      <a class="navbar-left" href="#">
        <%=image_tag ("ConneXt.png"), :class => "logo" %>
        <!--<img src="assets/">-->
      </a>
    </div>
</nav>

<div class="jumbotron col-sm-offset-4 col-sm-4">
    <div class="container">
    
      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Username</label>
        <input id="inputEmail" class="form-control" placeholder="Username" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <%= link_to "Sign in", app_pages_filter_url, {:style =>'color:#FFFFFF;', :class=> "btn btn-lg btn-primary btn-block"} %>
      </form>
    </div>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class = "container">
    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>
    <p class="navbar-text pull-left" display="inline-block">© 2017 - D@M:AS.</p>
  </div>
  <!--<div class="container">-->
  <!--  <a class="pull-right" href="#"> -->
  <!--    <%=image_tag ("X.png"), :class => "logo2 pull-right", :display=>"inline-block" %>-->
  <!--</div> -->
</div>