config/routes.rb
Rails.application.routes.draw do
  
  root 'application#signin'
  
  get 'app_pages/signin'

  get 'app_pages/filter'

  get 'app_pages/book'

  resources :appointments
  resources :doctors
  resources :organizations
  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :doctor
    
    scope :medicare, -> { where(doctor.organization.takes_medicare :true) }
    scope :slider, -> { where(doctor.organization.sliding_scale :true) }
    scope :specialty, -> { where(doctor.specialty :specialty) }
    scope :distance, -> (distance) { where("doctor.organization.distance < ?", params[:distance]) }
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.where(nil)
    filtering_params(params).each do |key, value|
      @appointment = @appointment.public_send(key, value) if value.present?
    end
  end
  
  # def search(search_medicare, search_slider, search_specialty, search_distance)
  #   return scoped unless search_medicare.present? || search_slider.preset? || search_specialty.present? || search_distance.present?
  #   where()


  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @doctors = Doctor.all
    @organizations = Organization.all
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "Appointment.pdf", :template => "appointments/show.html.erb"
      end
    end
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url+".pdf", notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def book
    @appointment.close
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:start_time, :date, :length, :open, :patient_birthdate, :patient_name, :doctor_id)
    end
    
    # A list of param names that can be used for filtering
    def filtering_params(params)
      params.slice(:medicare, :slider, :specialty, :distance)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <ul class="form-inputs" style="list-style-type: none">
    <li><%= @appointment.start_time %></li>
    <li><%= @appointment.date %></li>
    <li><%= @appointment.length %></li>
    <li><%= @appointment.open %></li>
    <li><%= f.input :patient_birthdate, start_year: Date.today.year - 110, end_year: Date.today.year  %></li>
    <li><%= f.input :patient_name %></li>
  </ul>

  <div class="form-actions">
    <%= f.button :submit, :style => "margin-left: 40px", :value => "Submit  Appointment" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="jumbotron">
    <h1 style="margin-left:20px;">Confirm Appointment</h1>

    <%= render 'form' %>
    
    <!--<%= link_to 'Show', @appointment %> |-->
    <%= link_to 'Back', app_pages_book_url, :style=>"margin-left:50px;" %>
</div>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>Date</th>
      <th>Length</th>
      <th>Open</th>
      <th>Patient birthdate</th>
      <th>Patient name</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.length %></td>
        <td><%= appointment.open %></td>
        <td><%= appointment.patient_birthdate %></td>
        <td><%= appointment.patient_name %></td>
        <td><%= appointment.doctor_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Organization:</strong>
  <%= @organizations.find(@doctors.find(@appointment.doctor_id).organization_id).name%>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @doctors.find(@appointment.doctor_id).name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<!--<p>-->
<!--  <strong>Length:</strong>-->
<!--  <%= @appointment.length %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Open:</strong>-->
<!--  <%= @appointment.open %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Patient birthdate:</strong>-->
<!--  <%= @appointment.patient_birthdate %>-->
<!--</p>-->

<p>
  <strong>Patient name:</strong>
  <%= @appointment.patient_name %>
</p>